name: Deploy AWS CDK and Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Compile TS to JS and Install dependencies
        run: |
          npm install
          npm install --save-dev @types/aws-lambda @types/node
          npm install -g typescript
          npx tsc --project tsconfig.json --outDir dist
          cp package.json dist/
          cd dist
          npm install -g aws-cdk
          npm install --only=prod
          npm run build
          ls -lR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Deploy CDK stack
        run: |
          cdk bootstrap
          cdk deploy --require-approval never
      - name: Verify deployment
        run: |
          echo "Deployment completed successfully."
